### ISSUE TITLE
Figure out testing of updated model attributes on acceptance tests

### ISSUE THREAD

**Issue by oliverbarnes** [oliverbarnes/old-participate-client#19]

**Comment by KatiRG** [comment]
Can you do something like this? Supposing you could define the Initiative model so that it knew what it was, then:

`expect(Initiative).to.have.isSupported('true');`

adapted from http://chaijs.com/guide/helpers/ (e.g. `expect(arthur).to.have.age.above(17);` )

Right now this gives:
ReferenceError: Can't find variable: Initiative

**Comment by oliverbarnes** [comment]
That would be the syntax, if we could get at the initiative instance. The example you're looking at is for a unit test, in an acceptance test we're working on the scope of the interface, not of the model itself. In Rails/Rspec it'd be possible to do 

``` ruby
initiative = Initiative.last
expect(initiative.is_supported).to eql true
```

But with ember acceptance/integration tests, I haven't found a way to do the equivalent
